version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        data_type: integer
        tests:
          - unique
          - not_null
      - name: first_name
        data_type: varchar
      - name: last_name
        data_type: varchar

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

  - name: stg_stores
    columns:
      - name: store_id
        tests:
          - unique
          - not_null

sources:
  - name: sources_db
    database: sources_db
    schema: main
    tables:
      - name: stores
        columns:
          - name: store_id
            data_type: varchar
          - name: store_name
            data_type: varchar
          - name: country
            data_type: varchar
