name: test_and_lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-and-lint:
    name: Run linters and tests ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch
      - name: Run linters and tests
        run: |
          hatch run linters
          hatch run tests
